export const GET_PROPERTIES = "GET_PROPERTIES";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const REMOVE_PROPERTY = "REMOVE_PROPERTY";
export const GET_SINGLE_PROPERTY = "GET_SINGLE_PROPERTY";
